[package]
name = "messages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.151", features = ["derive"]}
yew = {version = "0.20", features = ["csr"] }
chrono = "0.4.23"